### ISSUE TITLE
Does whisper provide any help to do timbre transfer for voice?

### ISSUE THREAD

**Issue by johndpope** [hmartelb/Pix2Pix-Timbre-Transfer#4]
Also this maybe of interest

https://twitter.com/johndpope/status/1573137950518685697?s=46&t=4acH8po_PyT2NjVS_XI2uQ

**Comment by johndpope** [comment]
Found this - https://github.com/archinetai/audio-diffusion-pytorch

**Comment by hmartelb** [comment]
Hi @johndpope, thanks for sharing! It's definitely worth taking a look into newer approaches, as my repo is a few years old already.
